language: node_js
sudo: false
node_js:
- 0.10.31
- '0.10'
- '0.11'
env:
  global:
  - LOG_LEVEL=error
  - secure: Nto0DJdtm5X9c0UxO3WDc1UJcDMr6iqonzEg8jsbv6WBcKx4QuZTwJQevKxqb6Tn3kiY4EAKMxZkBPUEwAtOSjDNXogOS1WbZZ+8KxcHB5eMqAtRUR0cT4MnyHFxHD/yKzUMlpMLPw9sBRJVXyj1S3oZtgMyvgrxvXbdi6gFCnI=
  - secure: TOpGyGYih+aDCljsnk93VEe+FRh8Ehh56Ycs1vFglWbC5HukgQ6gjrgpn28JUN1pV+XYIhfuDcvRNXLOBP4mX80c3LwClOh4AXzOf1VJcJyIGRVMCuCK9UgS37e/RsxgFczcu/MzJG/rCbt0lR46t6FQhqEBzmsbJV0oL5zA94M=
matrix:
  fast_finish: true
script: npm test
after_script: npm install codacy && cat ./coverage/lcov.info | codacy -d